name: MacOS CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup release environment
        run: |
          BUILD=$(git rev-list --count --first-parent HEAD)
          TODAY=$(date +"%d.%m.%y")
          echo "BUILD=${BUILD}" >> "$GITHUB_ENV"
          echo "TODAY=${TODAY}" >> "$GITHUB_ENV"
          echo "Build number ${BUILD}"

      - name: Install required packages
        run: sudo port install automake autoconf yasm pkgconfig gmake cmake
      - name: Install meson via pip
        run: pip3 install meson ninja

      - name: Configure linux (dev) (discord)
        run: ./configure --with-discord
      - name: Make linux (dev) (discord)
        run: make -j $(getconf _NPROCESSORS_ONLN)
      - name: Zip the necessary files
        run: zip -j linux-dev-discord.zip DerivedData/Posix-x86_64/onscripter-ru DerivedData/Posix-x86_64/Dependencies/onscrlib/lib/libdiscord_game_sdk.so
      - name: Clean
        run: make clean

      - name: Configure linux (release) (discord)
        run: ./configure --release-build --strip-binary --with-discord
      - name: Make linux (release) (discord)
        run: make -j $(getconf _NPROCESSORS_ONLN)
      - name: Zip the necessary files
        run: zip -j linux-release-discord.zip DerivedData/Posix-x86_64/onscripter-ru DerivedData/Posix-x86_64/Dependencies/onscrlib/lib/libdiscord_game_sdk.so
      - name: Clean
        run: |
          make clean
          rm -f DerivedData/Posix-x86_64/Dependencies/onscrlib/.pkgs/onscrlib DerivedData/Posix-x86_64/Dependencies/onscrlib/.pkgs/discord

      - name: Configure linux (dev)
        run: ./configure
      - name: Make linux (dev)
        run: make -j $(getconf _NPROCESSORS_ONLN)
      - name: Zip the necessary file
        run: zip -j linux-dev.zip DerivedData/Posix-x86_64/onscripter-ru
      - name: Clean
        run: make clean
      

      - name: Configure linux (release)
        run: ./configure --release-build --strip-binary
      - name: Make linux (release)
        run: make -j $(getconf _NPROCESSORS_ONLN)
      - name: Zip the necessary file
        run: zip -j linux-release.zip DerivedData/Posix-x86_64/onscripter-ru

      - name: Upload files
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          replacesArtifacts: false
          tag: z${{ env.BUILD }}
          name: ONScripter-ru r${{ env.BUILD }}
          artifacts: "*.zip"