name: MacOS CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup release environment
        run: |
          BUILD=$(git rev-list --count --first-parent HEAD)
          TODAY=$(date +"%d.%m.%y")
          echo "BUILD=${BUILD}" >> "$GITHUB_ENV"
          echo "TODAY=${TODAY}" >> "$GITHUB_ENV"
          echo "Build number ${BUILD}"
          
      - name: Install required packages
        run: brew install automake autoconf yasm pkgconfig make cmake gnu-tar
        
      - name: Install meson via pip
        run: pip3 install meson ninja
        
      #- name: Setup upterm session
      #  uses: lhotari/action-upterm@v1
      #  with:
      #  ## limits ssh access and adds the ssh public key for the user which triggered the workflow
      #    limit-access-to-actor: true
      #    ## limits ssh access and adds the ssh public keys of the listed GitHub users
      #    limit-access-to-users: m3t4f1v3
        
      - name: try building
        run: xcodebuild -target onscripter-ru-osx -configuration Debug || exit 1

      - name: Upload files
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          replacesArtifacts: false
          tag: z${{ env.BUILD }}
          name: ONScripter-ru r${{ env.BUILD }}
          artifacts: "*.zip"
