name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install required packages
      run: sudo apt install yasm libreadline-dev libasound-dev libgl1-mesa-dev libegl1-mesa-dev libxrandr-dev python3-pip autopoint po4a binutils-mingw-w64-i686 gcc-mingw-w64-i686
    - name: Install meson via pip
      run: pip3 install meson ninja
    - name: Configure linux (dev)
      run: ./configure
    - name: make
      run: make -j $(getconf _NPROCESSORS_ONLN)
    - name: Upload compiled binaries to github
      uses: softprops/action-gh-release@v0.1.14
      with:
        files: DerivedData/Posix-x86_64/onscripter-ru