name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup release
      uses: actions/create-release@v1
      id: create_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD: ${$(git rev-list --count --first-parent master)}
      with:
        tag_name: z${{ env.BUILD }}
        release_name: ONScripter-ru r${{ env.BUILD }}
        draft: false
        prerelease: false
    - name: Install required packages
      run: sudo apt install yasm libreadline-dev libasound-dev libgl1-mesa-dev libegl1-mesa-dev libxrandr-dev python3-pip autopoint po4a binutils-mingw-w64-i686 gcc-mingw-w64-i686
    - name: Install meson via pip
      run: pip3 install meson ninja
    - name: Configure linux (dev)
      run: ./configure
    - name: Make linux (dev)
      run: make -j $(getconf _NPROCESSORS_ONLN)
    - name: Upload (dev)
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: DerivedData/Posix-x86_64/onscripter-ru
        asset_name: onscripter-ru-linux-r${{ env.BUILD }}-dev
        asset_content_type: application/x-pie-executable
